services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./data/uploads:/app/uploads
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./data/sql_app.db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./data:/app/data:ro
      - ./data/uploads:/app/uploads:ro
    depends_on:
      - backend
    networks:
      - app-network

  # test:
  #   build:
  #     context: .
  #     dockerfile: tests/Dockerfile.test
  #   volumes:
  #     - .:/app
  #   environment:
  #     - SQLALCHEMY_DATABASE_URL=sqlite:///./test.db
  #   networks:
  #     - app-network

volumes:
  backend_data:
  shared_uploads:

networks:
  app-network:
    driver: bridge
