"""initial

Revision ID: 85305a3975e8
Revises: 
Create Date: 2025-01-11 11:37:46.841454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85305a3975e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True, comment='工程名稱'),
    sa.Column('contract_number', sa.String(), nullable=True, comment='契約編號'),
    sa.Column('contractor', sa.String(), nullable=True, comment='承攬廠商'),
    sa.Column('location', sa.String(), nullable=True, comment='施工地點'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_contract_number'), 'projects', ['contract_number'], unique=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('pcces_code', sa.String(), nullable=True, comment='PCCES編號'),
    sa.Column('name', sa.String(), nullable=True, comment='項目名稱'),
    sa.Column('unit', sa.String(), nullable=True, comment='單位'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='契約數量'),
    sa.Column('unit_price', sa.Float(), nullable=True, comment='契約單價'),
    sa.Column('total_price', sa.Float(), nullable=True, comment='契約複價'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_items_id'), 'contract_items', ['id'], unique=False)
    op.create_index(op.f('ix_contract_items_pcces_code'), 'contract_items', ['pcces_code'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True, comment='抽查表名稱'),
    sa.Column('inspection_time', sa.DateTime(), nullable=True, comment='抽查時間'),
    sa.Column('location', sa.String(), nullable=True, comment='抽查地點'),
    sa.Column('file_path', sa.String(), nullable=True, comment='電子檔路徑'),
    sa.Column('is_pass', sa.String(), nullable=True, comment='是否合格'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('contract_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True, comment='自定義試驗名稱'),
    sa.Column('test_item', sa.String(), nullable=True, comment='對應試驗項目'),
    sa.Column('test_sets', sa.Integer(), nullable=True, comment='試驗組數'),
    sa.Column('test_result', sa.String(), nullable=True, comment='試驗結果'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('quality_test_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True, comment='檔案名稱'),
    sa.Column('file_path', sa.String(), nullable=True, comment='圖片路徑'),
    sa.Column('thumbnail_path', sa.String(), nullable=True, comment='縮圖路徑'),
    sa.Column('description', sa.String(), nullable=True, comment='圖片描述'),
    sa.Column('exif_data', sa.String(), nullable=True, comment='EXIF信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quality_test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_contract_items_pcces_code'), table_name='contract_items')
    op.drop_index(op.f('ix_contract_items_id'), table_name='contract_items')
    op.drop_table('contract_items')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_contract_number'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
